{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.2.jar",
          "url": "spring-boot-starter-tomcat-3.4.2.jar",
          "size": 4793,
          "sha512": "d3f1cd14cbb2f18c1a2332c600f81d8e177ac01d2feea57cc3f5728c933366729b225f13a7392651b9f792d23aae17b9a69f6d3a56511372d328624d58f59ba6",
          "sha256": "4e0b90f2968334c314109d3f0a7cda14306a238c33a7657abb0d11429217b431",
          "sha1": "aa345bdd83adc80db5bc6ac4a711460396ad17ef",
          "md5": "db10d2f4063dadfa70843a6017f03908"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.2.jar",
          "url": "spring-boot-starter-tomcat-3.4.2.jar",
          "size": 4793,
          "sha512": "d3f1cd14cbb2f18c1a2332c600f81d8e177ac01d2feea57cc3f5728c933366729b225f13a7392651b9f792d23aae17b9a69f6d3a56511372d328624d58f59ba6",
          "sha256": "4e0b90f2968334c314109d3f0a7cda14306a238c33a7657abb0d11429217b431",
          "sha1": "aa345bdd83adc80db5bc6ac4a711460396ad17ef",
          "md5": "db10d2f4063dadfa70843a6017f03908"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.2-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.4.2-javadoc.jar",
          "size": 4793,
          "sha512": "ec7537c6b144b81e1ba5d6cdf93c8df825e72599c9925b3e5008bd61e84f5942c3dd4ab8d5c0427f3e28c5d509ebb5a2f1be2da7464ffce815ee5c0abd046248",
          "sha256": "c5caac9a5be4bc113fa2b0201eeb8b8a07f79d2ac5889c55590f8be8f6747947",
          "sha1": "05dd4ae777b520ae27cea67a96f15e2bd9ec4632",
          "md5": "614b1b52b8e948ff290acf305ee688f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.2-sources.jar",
          "url": "spring-boot-starter-tomcat-3.4.2-sources.jar",
          "size": 4793,
          "sha512": "ec7537c6b144b81e1ba5d6cdf93c8df825e72599c9925b3e5008bd61e84f5942c3dd4ab8d5c0427f3e28c5d509ebb5a2f1be2da7464ffce815ee5c0abd046248",
          "sha256": "c5caac9a5be4bc113fa2b0201eeb8b8a07f79d2ac5889c55590f8be8f6747947",
          "sha1": "05dd4ae777b520ae27cea67a96f15e2bd9ec4632",
          "md5": "614b1b52b8e948ff290acf305ee688f7"
        }
      ]
    }
  ]
}
