{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.2.jar",
          "url": "spring-webmvc-6.2.2.jar",
          "size": 1088576,
          "sha512": "097bd11ee79c1dbd35218d5add4339e344037289e9b8bfb4145f4305402a22ae0305337d1e6d2e3130803d8520ead537677f528ed503d1cd341fed66a70966ca",
          "sha256": "af8118c189ef69925c0a719ccb84b019bbb3523416ac656403f04d42c122d9dd",
          "sha1": "9b1aeb179ba9667bc78a4a5cec4ec8087db404d7",
          "md5": "4e6646bba51f1ade23c69a6ac2f4ada4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.2.jar",
          "url": "spring-webmvc-6.2.2.jar",
          "size": 1088576,
          "sha512": "097bd11ee79c1dbd35218d5add4339e344037289e9b8bfb4145f4305402a22ae0305337d1e6d2e3130803d8520ead537677f528ed503d1cd341fed66a70966ca",
          "sha256": "af8118c189ef69925c0a719ccb84b019bbb3523416ac656403f04d42c122d9dd",
          "sha1": "9b1aeb179ba9667bc78a4a5cec4ec8087db404d7",
          "md5": "4e6646bba51f1ade23c69a6ac2f4ada4"
        }
      ]
    }
  ]
}
